name: floof
description: Josh's 18th birthday present!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.14
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.12
  flutter:
    sdk: flutter
  image_gallery_saver: ^1.7.1
  internet_connection_checker: ^0.0.1+3
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  # this version fixes a bug
  # see https://stackoverflow.com/questions/70404718/error-with-photoview-looking-up-a-deactivated-widgets-ancestor-is-unsafe/71010204#71010204
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
  shared_preferences: ^2.0.12
  url_launcher: ^6.0.18
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
  fonts:
    - family: PinyonScript
      fonts:
        - asset: assets/fonts/PinyonScript-Regular.ttf
