name: floof
description: Josh's 18th birthday present!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  audioplayers: ^0.20.1
  cloud_firestore: ^3.1.7
  firebase_core: ^1.12.0
  flutter:
    sdk: flutter
  image_gallery_saver: ^1.7.1
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  shared_preferences: ^2.0.12
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/picture_row/
    - assets/sounds/
