// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbXZGQwRA1p2s0ih9WzZ6xMppxXKsl2Q8',
    appId: '1:253341352596:android:9b4da087456f9acdeeea81',
    messagingSenderId: '253341352596',
    projectId: 'josh-s-birthday-app',
    storageBucket: 'josh-s-birthday-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMenKIQ8bd4MERLieFkOmRfoU0uE93TDo',
    appId: '1:253341352596:ios:84c989d0abcc163beeea81',
    messagingSenderId: '253341352596',
    projectId: 'josh-s-birthday-app',
    storageBucket: 'josh-s-birthday-app.appspot.com',
    iosClientId: '253341352596-pgss03n7759hegrvcn7j52nhiqm1j8fb.apps.googleusercontent.com',
    iosBundleId: 'com.benweschler.floof',
  );
}
